# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dab.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QHeaderView, QLabel, QLineEdit, QProgressBar,
    QPushButton, QScrollArea, QScrollBar, QSizePolicy,
    QTableWidget, QTableWidgetItem, QVBoxLayout, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1476, 866)
        icon = QIcon()
        icon.addFile(u"radio.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        Form.setWindowIcon(icon)
        self.groupBoxSlideshow = QGroupBox(Form)
        self.groupBoxSlideshow.setObjectName(u"groupBoxSlideshow")
        self.groupBoxSlideshow.setGeometry(QRect(430, 10, 441, 441))
        self.lineEditPacket = QLineEdit(self.groupBoxSlideshow)
        self.lineEditPacket.setObjectName(u"lineEditPacket")
        self.lineEditPacket.setGeometry(QRect(10, 360, 51, 25))
        self.lineEditPacket.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEditPictureName = QLineEdit(self.groupBoxSlideshow)
        self.lineEditPictureName.setObjectName(u"lineEditPictureName")
        self.lineEditPictureName.setGeometry(QRect(70, 360, 361, 25))
        self.lineEditPictureName.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.labelPicture = QLabel(self.groupBoxSlideshow)
        self.labelPicture.setObjectName(u"labelPicture")
        self.labelPicture.setGeometry(QRect(10, 30, 421, 321))
        self.labelPicture.setPixmap(QPixmap(u"DAB_Shield.jpg"))
        self.labelPicture.setScaledContents(True)
        self.checkBoxSaveImage = QCheckBox(self.groupBoxSlideshow)
        self.checkBoxSaveImage.setObjectName(u"checkBoxSaveImage")
        self.checkBoxSaveImage.setGeometry(QRect(10, 400, 141, 31))
        self.labelSavedImage = QLabel(self.groupBoxSlideshow)
        self.labelSavedImage.setObjectName(u"labelSavedImage")
        self.labelSavedImage.setGeometry(QRect(160, 400, 271, 31))
        self.groupBoxValues = QGroupBox(Form)
        self.groupBoxValues.setObjectName(u"groupBoxValues")
        self.groupBoxValues.setGeometry(QRect(880, 10, 341, 151))
        self.label1 = QLabel(self.groupBoxValues)
        self.label1.setObjectName(u"label1")
        self.label1.setGeometry(QRect(10, 30, 67, 17))
        self.progressBarRSSI = QProgressBar(self.groupBoxValues)
        self.progressBarRSSI.setObjectName(u"progressBarRSSI")
        self.progressBarRSSI.setGeometry(QRect(80, 30, 161, 23))
        self.progressBarRSSI.setBaseSize(QSize(0, 0))
        self.progressBarRSSI.setValue(10)
        self.progressBarRSSI.setTextVisible(False)
        self.progressBarSNR = QProgressBar(self.groupBoxValues)
        self.progressBarSNR.setObjectName(u"progressBarSNR")
        self.progressBarSNR.setGeometry(QRect(80, 60, 161, 23))
        self.progressBarSNR.setMaximum(20)
        self.progressBarSNR.setValue(10)
        self.progressBarSNR.setTextVisible(False)
        self.label2 = QLabel(self.groupBoxValues)
        self.label2.setObjectName(u"label2")
        self.label2.setGeometry(QRect(10, 60, 67, 17))
        self.label3 = QLabel(self.groupBoxValues)
        self.label3.setObjectName(u"label3")
        self.label3.setGeometry(QRect(10, 90, 67, 17))
        self.label4 = QLabel(self.groupBoxValues)
        self.label4.setObjectName(u"label4")
        self.label4.setGeometry(QRect(10, 120, 67, 17))
        self.progressBarCNR = QProgressBar(self.groupBoxValues)
        self.progressBarCNR.setObjectName(u"progressBarCNR")
        self.progressBarCNR.setGeometry(QRect(80, 90, 161, 23))
        self.progressBarCNR.setMaximum(54)
        self.progressBarCNR.setValue(10)
        self.progressBarCNR.setTextVisible(False)
        self.progressBarFIC = QProgressBar(self.groupBoxValues)
        self.progressBarFIC.setObjectName(u"progressBarFIC")
        self.progressBarFIC.setGeometry(QRect(80, 120, 161, 23))
        self.progressBarFIC.setBaseSize(QSize(0, 0))
        font = QFont()
        font.setPointSize(9)
        self.progressBarFIC.setFont(font)
        self.progressBarFIC.setValue(24)
        self.progressBarFIC.setTextVisible(False)
        self.labelRSSI = QLabel(self.groupBoxValues)
        self.labelRSSI.setObjectName(u"labelRSSI")
        self.labelRSSI.setGeometry(QRect(260, 30, 67, 17))
        self.labelSNR = QLabel(self.groupBoxValues)
        self.labelSNR.setObjectName(u"labelSNR")
        self.labelSNR.setGeometry(QRect(260, 60, 67, 17))
        self.labelCNR = QLabel(self.groupBoxValues)
        self.labelCNR.setObjectName(u"labelCNR")
        self.labelCNR.setGeometry(QRect(260, 90, 67, 17))
        self.labelFIC = QLabel(self.groupBoxValues)
        self.labelFIC.setObjectName(u"labelFIC")
        self.labelFIC.setGeometry(QRect(260, 120, 67, 17))
        self.groupBoxVolume = QGroupBox(Form)
        self.groupBoxVolume.setObjectName(u"groupBoxVolume")
        self.groupBoxVolume.setGeometry(QRect(880, 170, 341, 101))
        self.horizontalScrollBarVolume = QScrollBar(self.groupBoxVolume)
        self.horizontalScrollBarVolume.setObjectName(u"horizontalScrollBarVolume")
        self.horizontalScrollBarVolume.setGeometry(QRect(20, 30, 311, 31))
        self.horizontalScrollBarVolume.setMaximum(60)
        self.horizontalScrollBarVolume.setOrientation(Qt.Orientation.Horizontal)
        self.checkBoxMute = QCheckBox(self.groupBoxVolume)
        self.checkBoxMute.setObjectName(u"checkBoxMute")
        self.checkBoxMute.setGeometry(QRect(20, 70, 61, 23))
        self.checkBoxMono = QCheckBox(self.groupBoxVolume)
        self.checkBoxMono.setObjectName(u"checkBoxMono")
        self.checkBoxMono.setGeometry(QRect(100, 70, 61, 23))
        self.labelVolume = QLabel(self.groupBoxVolume)
        self.labelVolume.setObjectName(u"labelVolume")
        self.labelVolume.setGeometry(QRect(250, 70, 67, 17))
        self.labelVolume.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.labelOuput = QLabel(self.groupBoxVolume)
        self.labelOuput.setObjectName(u"labelOuput")
        self.labelOuput.setGeometry(QRect(170, 70, 81, 21))
        self.groupBoxAudioInfo = QGroupBox(Form)
        self.groupBoxAudioInfo.setObjectName(u"groupBoxAudioInfo")
        self.groupBoxAudioInfo.setGeometry(QRect(880, 280, 341, 81))
        self.labelBitRate = QLabel(self.groupBoxAudioInfo)
        self.labelBitRate.setObjectName(u"labelBitRate")
        self.labelBitRate.setGeometry(QRect(10, 30, 221, 17))
        self.labelSampleRate = QLabel(self.groupBoxAudioInfo)
        self.labelSampleRate.setObjectName(u"labelSampleRate")
        self.labelSampleRate.setGeometry(QRect(10, 50, 221, 17))
        self.groupBoxScanService = QGroupBox(Form)
        self.groupBoxScanService.setObjectName(u"groupBoxScanService")
        self.groupBoxScanService.setGeometry(QRect(150, 10, 271, 71))
        self.pushButtonScan = QPushButton(self.groupBoxScanService)
        self.pushButtonScan.setObjectName(u"pushButtonScan")
        self.pushButtonScan.setGeometry(QRect(8, 24, 251, 31))
        self.groupBoxCurrentService = QGroupBox(Form)
        self.groupBoxCurrentService.setObjectName(u"groupBoxCurrentService")
        self.groupBoxCurrentService.setGeometry(QRect(430, 460, 791, 141))
        self.lineEditCurrentService = QLineEdit(self.groupBoxCurrentService)
        self.lineEditCurrentService.setObjectName(u"lineEditCurrentService")
        self.lineEditCurrentService.setGeometry(QRect(10, 30, 211, 25))
        self.lineEditTitle = QLineEdit(self.groupBoxCurrentService)
        self.lineEditTitle.setObjectName(u"lineEditTitle")
        self.lineEditTitle.setGeometry(QRect(10, 60, 771, 31))
        self.lineEditArtistDLS = QLineEdit(self.groupBoxCurrentService)
        self.lineEditArtistDLS.setObjectName(u"lineEditArtistDLS")
        self.lineEditArtistDLS.setGeometry(QRect(10, 100, 771, 31))
        self.checkBoxArtistTitle = QCheckBox(self.groupBoxCurrentService)
        self.checkBoxArtistTitle.setObjectName(u"checkBoxArtistTitle")
        self.checkBoxArtistTitle.setGeometry(QRect(230, 30, 111, 23))
        self.groupBoxOnOff = QGroupBox(Form)
        self.groupBoxOnOff.setObjectName(u"groupBoxOnOff")
        self.groupBoxOnOff.setGeometry(QRect(20, 10, 120, 161))
        self.pushButtonOn = QPushButton(self.groupBoxOnOff)
        self.pushButtonOn.setObjectName(u"pushButtonOn")
        self.pushButtonOn.setGeometry(QRect(10, 130, 51, 25))
        self.pushButtonOff = QPushButton(self.groupBoxOnOff)
        self.pushButtonOff.setObjectName(u"pushButtonOff")
        self.pushButtonOff.setGeometry(QRect(70, 130, 41, 25))
        self.verticalLayoutWidget = QWidget(self.groupBoxOnOff)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 30, 101, 91))
        self.layoutPower = QVBoxLayout(self.verticalLayoutWidget)
        self.layoutPower.setObjectName(u"layoutPower")
        self.layoutPower.setContentsMargins(0, 0, 0, 0)
        self.groupBoxCheck = QGroupBox(Form)
        self.groupBoxCheck.setObjectName(u"groupBoxCheck")
        self.groupBoxCheck.setGeometry(QRect(20, 610, 1201, 151))
        self.labelBufferOut = QLabel(self.groupBoxCheck)
        self.labelBufferOut.setObjectName(u"labelBufferOut")
        self.labelBufferOut.setGeometry(QRect(10, 30, 81, 17))
        self.labelBufferIn = QLabel(self.groupBoxCheck)
        self.labelBufferIn.setObjectName(u"labelBufferIn")
        self.labelBufferIn.setGeometry(QRect(10, 70, 67, 17))
        self.lineEditBufferOut = QLineEdit(self.groupBoxCheck)
        self.lineEditBufferOut.setObjectName(u"lineEditBufferOut")
        self.lineEditBufferOut.setGeometry(QRect(100, 30, 1091, 25))
        font1 = QFont()
        font1.setFamilies([u"Tlwg Typo"])
        font1.setBold(True)
        self.lineEditBufferOut.setFont(font1)
        self.lineEditBufferIn = QLineEdit(self.groupBoxCheck)
        self.lineEditBufferIn.setObjectName(u"lineEditBufferIn")
        self.lineEditBufferIn.setGeometry(QRect(100, 70, 1091, 25))
        font2 = QFont()
        font2.setFamilies([u"Tlwg Typist"])
        font2.setBold(True)
        self.lineEditBufferIn.setFont(font2)
        self.labelAddress = QLabel(self.groupBoxCheck)
        self.labelAddress.setObjectName(u"labelAddress")
        self.labelAddress.setGeometry(QRect(10, 110, 67, 17))
        self.lineEditAddress = QLineEdit(self.groupBoxCheck)
        self.lineEditAddress.setObjectName(u"lineEditAddress")
        self.lineEditAddress.setGeometry(QRect(100, 110, 1091, 25))
        self.lineEditAddress.setFont(font1)
        self.groupBoxTest = QGroupBox(Form)
        self.groupBoxTest.setObjectName(u"groupBoxTest")
        self.groupBoxTest.setGeometry(QRect(150, 80, 271, 91))
        self.labelInformation = QLabel(self.groupBoxTest)
        self.labelInformation.setObjectName(u"labelInformation")
        self.labelInformation.setGeometry(QRect(10, 20, 251, 61))
        self.groupBoxPresets = QGroupBox(Form)
        self.groupBoxPresets.setObjectName(u"groupBoxPresets")
        self.groupBoxPresets.setGeometry(QRect(1230, 90, 231, 671))
        self.pushButtonPreset1 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset1.setObjectName(u"pushButtonPreset1")
        self.pushButtonPreset1.setGeometry(QRect(10, 30, 211, 41))
        self.pushButtonPreset2 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset2.setObjectName(u"pushButtonPreset2")
        self.pushButtonPreset2.setGeometry(QRect(10, 80, 211, 41))
        self.pushButtonPreset3 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset3.setObjectName(u"pushButtonPreset3")
        self.pushButtonPreset3.setGeometry(QRect(10, 130, 211, 41))
        self.pushButtonPreset4 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset4.setObjectName(u"pushButtonPreset4")
        self.pushButtonPreset4.setGeometry(QRect(10, 180, 211, 41))
        self.pushButtonPreset5 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset5.setObjectName(u"pushButtonPreset5")
        self.pushButtonPreset5.setGeometry(QRect(10, 230, 211, 41))
        self.pushButtonPreset6 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset6.setObjectName(u"pushButtonPreset6")
        self.pushButtonPreset6.setGeometry(QRect(10, 280, 211, 41))
        self.pushButtonPreset7 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset7.setObjectName(u"pushButtonPreset7")
        self.pushButtonPreset7.setGeometry(QRect(10, 330, 211, 41))
        self.pushButtonPreset8 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset8.setObjectName(u"pushButtonPreset8")
        self.pushButtonPreset8.setGeometry(QRect(10, 380, 211, 41))
        self.pushButtonPreset9 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset9.setObjectName(u"pushButtonPreset9")
        self.pushButtonPreset9.setGeometry(QRect(10, 430, 211, 41))
        self.pushButtonPreset10 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset10.setObjectName(u"pushButtonPreset10")
        self.pushButtonPreset10.setGeometry(QRect(10, 480, 211, 41))
        self.pushButtonPreset11 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset11.setObjectName(u"pushButtonPreset11")
        self.pushButtonPreset11.setGeometry(QRect(10, 530, 211, 41))
        self.pushButtonPreset12 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset12.setObjectName(u"pushButtonPreset12")
        self.pushButtonPreset12.setGeometry(QRect(10, 580, 211, 41))
        self.pushButtonMemory = QPushButton(self.groupBoxPresets)
        self.pushButtonMemory.setObjectName(u"pushButtonMemory")
        self.pushButtonMemory.setGeometry(QRect(64, 630, 111, 24))
        self.groupBoxStatus = QGroupBox(Form)
        self.groupBoxStatus.setObjectName(u"groupBoxStatus")
        self.groupBoxStatus.setGeometry(QRect(20, 770, 1441, 71))
        self.toolStripStatusLabel1 = QLabel(self.groupBoxStatus)
        self.toolStripStatusLabel1.setObjectName(u"toolStripStatusLabel1")
        self.toolStripStatusLabel1.setGeometry(QRect(60, 20, 221, 41))
        self.toolStripStatusLabel2 = QLabel(self.groupBoxStatus)
        self.toolStripStatusLabel2.setObjectName(u"toolStripStatusLabel2")
        self.toolStripStatusLabel2.setGeometry(QRect(330, 20, 201, 41))
        self.toolStripStatusLabel3 = QLabel(self.groupBoxStatus)
        self.toolStripStatusLabel3.setObjectName(u"toolStripStatusLabel3")
        self.toolStripStatusLabel3.setGeometry(QRect(590, 26, 231, 31))
        self.toolStripStatusLabel4 = QLabel(self.groupBoxStatus)
        self.toolStripStatusLabel4.setObjectName(u"toolStripStatusLabel4")
        self.toolStripStatusLabel4.setGeometry(QRect(860, 20, 411, 41))
        self.groupBoxServicesList = QGroupBox(Form)
        self.groupBoxServicesList.setObjectName(u"groupBoxServicesList")
        self.groupBoxServicesList.setGeometry(QRect(20, 180, 401, 421))
        self.scrollArea = QScrollArea(self.groupBoxServicesList)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(10, 30, 381, 351))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 379, 349))
        self.tableWidgetViewServices = QTableWidget(self.scrollAreaWidgetContents)
        if (self.tableWidgetViewServices.columnCount() < 8):
            self.tableWidgetViewServices.setColumnCount(8)
        if (self.tableWidgetViewServices.rowCount() < 60):
            self.tableWidgetViewServices.setRowCount(60)
        self.tableWidgetViewServices.setObjectName(u"tableWidgetViewServices")
        self.tableWidgetViewServices.setGeometry(QRect(10, 10, 361, 331))
        self.tableWidgetViewServices.setMinimumSize(QSize(8, 0))
        self.tableWidgetViewServices.setRowCount(60)
        self.tableWidgetViewServices.setColumnCount(8)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButtonSaveList = QPushButton(self.groupBoxServicesList)
        self.pushButtonSaveList.setObjectName(u"pushButtonSaveList")
        self.pushButtonSaveList.setGeometry(QRect(244, 383, 141, 31))
        self.groupBoxArea = QGroupBox(Form)
        self.groupBoxArea.setObjectName(u"groupBoxArea")
        self.groupBoxArea.setGeometry(QRect(1230, 9, 231, 71))
        self.comboBoxAreas = QComboBox(self.groupBoxArea)
        self.comboBoxAreas.setObjectName(u"comboBoxAreas")
        self.comboBoxAreas.setGeometry(QRect(10, 30, 211, 31))
        self.groupBoxDateTime = QGroupBox(Form)
        self.groupBoxDateTime.setObjectName(u"groupBoxDateTime")
        self.groupBoxDateTime.setGeometry(QRect(880, 370, 341, 80))
        self.lineEditDateTime = QLineEdit(self.groupBoxDateTime)
        self.lineEditDateTime.setObjectName(u"lineEditDateTime")
        self.lineEditDateTime.setGeometry(QRect(10, 30, 321, 31))
        self.lineEditDateTime.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.retranslateUi(Form)
        self.horizontalScrollBarVolume.valueChanged.connect(self.labelVolume.setNum)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"DAB Tuner Si4684", None))
        self.groupBoxSlideshow.setTitle(QCoreApplication.translate("Form", u"Slideshow", None))
        self.lineEditPacket.setText(QCoreApplication.translate("Form", u"0", None))
        self.lineEditPictureName.setText(QCoreApplication.translate("Form", u".jpg", None))
        self.labelPicture.setText("")
        self.checkBoxSaveImage.setText(QCoreApplication.translate("Form", u"Save the next image", None))
        self.labelSavedImage.setText("")
        self.groupBoxValues.setTitle(QCoreApplication.translate("Form", u"Values", None))
        self.label1.setText(QCoreApplication.translate("Form", u"RSSI", None))
        self.label2.setText(QCoreApplication.translate("Form", u"SNR", None))
        self.label3.setText(QCoreApplication.translate("Form", u"CNR", None))
        self.label4.setText(QCoreApplication.translate("Form", u"FIC", None))
        self.labelRSSI.setText(QCoreApplication.translate("Form", u"dB V", None))
        self.labelSNR.setText(QCoreApplication.translate("Form", u"dB", None))
        self.labelCNR.setText(QCoreApplication.translate("Form", u"dB", None))
        self.labelFIC.setText(QCoreApplication.translate("Form", u"0", None))
        self.groupBoxVolume.setTitle(QCoreApplication.translate("Form", u"Volume", None))
        self.checkBoxMute.setText(QCoreApplication.translate("Form", u"Mute", None))
        self.checkBoxMono.setText(QCoreApplication.translate("Form", u"Mono", None))
        self.labelVolume.setText(QCoreApplication.translate("Form", u"0", None))
        self.labelOuput.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" color:#00aa00;\">Analog output</span></p></body></html>", None))
        self.groupBoxAudioInfo.setTitle(QCoreApplication.translate("Form", u"Audio Info", None))
        self.labelBitRate.setText(QCoreApplication.translate("Form", u"Bit Rate :", None))
        self.labelSampleRate.setText(QCoreApplication.translate("Form", u"Sample Rate :", None))
        self.groupBoxScanService.setTitle(QCoreApplication.translate("Form", u"Scan Service", None))
        self.pushButtonScan.setText(QCoreApplication.translate("Form", u"Scan", None))
        self.groupBoxCurrentService.setTitle(QCoreApplication.translate("Form", u"Current Service", None))
        self.checkBoxArtistTitle.setText(QCoreApplication.translate("Form", u"Artist - Title", None))
        self.groupBoxOnOff.setTitle(QCoreApplication.translate("Form", u"On/Off", None))
        self.pushButtonOn.setText(QCoreApplication.translate("Form", u"On", None))
        self.pushButtonOff.setText(QCoreApplication.translate("Form", u"Off", None))
        self.groupBoxCheck.setTitle(QCoreApplication.translate("Form", u"Check", None))
        self.labelBufferOut.setText(QCoreApplication.translate("Form", u"Buffer Out", None))
        self.labelBufferIn.setText(QCoreApplication.translate("Form", u"Buffer In", None))
        self.labelAddress.setText(QCoreApplication.translate("Form", u"Address", None))
        self.groupBoxTest.setTitle(QCoreApplication.translate("Form", u"Information", None))
        self.labelInformation.setText(QCoreApplication.translate("Form", u"DAB+ application with Python 3 and PySide 6", None))
        self.groupBoxPresets.setTitle(QCoreApplication.translate("Form", u"Presets", None))
        self.pushButtonPreset1.setText(QCoreApplication.translate("Form", u"Preset #1", None))
        self.pushButtonPreset2.setText(QCoreApplication.translate("Form", u"Preset #2", None))
        self.pushButtonPreset3.setText(QCoreApplication.translate("Form", u"Preset #3", None))
        self.pushButtonPreset4.setText(QCoreApplication.translate("Form", u"Preset #4", None))
        self.pushButtonPreset5.setText(QCoreApplication.translate("Form", u"Preset #5", None))
        self.pushButtonPreset6.setText(QCoreApplication.translate("Form", u"Preset #6", None))
        self.pushButtonPreset7.setText(QCoreApplication.translate("Form", u"Preset #7", None))
        self.pushButtonPreset8.setText(QCoreApplication.translate("Form", u"Preset #8", None))
        self.pushButtonPreset9.setText(QCoreApplication.translate("Form", u"Preset #9", None))
        self.pushButtonPreset10.setText(QCoreApplication.translate("Form", u"Preset #10", None))
        self.pushButtonPreset11.setText(QCoreApplication.translate("Form", u"Preset #11", None))
        self.pushButtonPreset12.setText(QCoreApplication.translate("Form", u"Preset #12", None))
        self.pushButtonMemory.setText(QCoreApplication.translate("Form", u"Change this list", None))
        self.groupBoxStatus.setTitle(QCoreApplication.translate("Form", u"Status", None))
        self.toolStripStatusLabel1.setText(QCoreApplication.translate("Form", u"DAB Tuner", None))
        self.toolStripStatusLabel2.setText(QCoreApplication.translate("Form", u"PIC18LF25K50 / Si4684", None))
        self.toolStripStatusLabel3.setText(QCoreApplication.translate("Form", u"DAB is inactive", None))
        self.toolStripStatusLabel4.setText(QCoreApplication.translate("Form", u"PIC Firmware : 1.0.3 / Si Firmware revision : 6.0.10", None))
        self.groupBoxServicesList.setTitle(QCoreApplication.translate("Form", u"Services List", None))
        self.pushButtonSaveList.setText(QCoreApplication.translate("Form", u"Save this services list", None))
        self.groupBoxArea.setTitle(QCoreApplication.translate("Form", u"Areas", None))
        self.groupBoxDateTime.setTitle(QCoreApplication.translate("Form", u"Date and Time", None))
    # retranslateUi

